server:
  port: 8080

spring:
  application:
    name: jwt-redis
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://mariadb:3321/namu-jwt-test
    url: jdbc:mariadb://localhost:3321/namu-jwt-test
    username: namu-jwt-test
    password: 1234

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  redis:
#    host: redis
    host: localhost
    port: 6379
    password: 1234

  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
#    bootstrap-servers: kafka:19092  # Kafka 클라이언트가 Kafka 클러스터와 연결하는 데 필요한 브로커 주소
    consumer:
      group-id: video-processing-group
      auto-offset-reset: earliest
    producer:
      acks: all  # 모든 리더 및 팔로워가 메시지를 확인해야 함
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://schema-registry:8081

  minio:
#    endpoint: http://minio:9000
    endpoint: http://localhost:9000
    accessKey: admin
    secretKey: admin123
    bucket: di-bucket

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    lazy-loading-enabled: true  # Lazy Loading 활성화
    aggressive-lazy-loading: false  # 필요할 때만 로딩

