server:
  port: 8080

spring:
  application:
    name: jwt-redis

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3321/namu-jwt-test
    username: namu-jwt-test
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    lazy-loading-enabled: true  # Lazy Loading 활성화
    aggressive-lazy-loading: false  # 필요할 때만 로딩

