server:
  port: 9080

spring:
  application:
    name: jwt-redis
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3321/namu-jwt-test
    username: namu-jwt-test
    password: 1234


  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: video-processing-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://localhost:8081\


mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    lazy-loading-enabled: true  # Lazy Loading 활성화
    aggressive-lazy-loading: false  # 필요할 때만 로딩

