server:
  port: 8080

spring:
  application:
    name: jwt-redis
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3321/namu-jwt-test
    username: namu-jwt-test
    password: 1234


  redis:
    host: redis
    port: 6379
    password: 1234

  jpa:
    open-in-view: false

  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: kafka:19092  # Kafka 클라이언트가 Kafka 클러스터와 연결하는 데 필요한 브로커 주소
    consumer:
      group-id: video-processing-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://schema-registry:8081

  minio:
    endpoint: http://minio:9000
    accessKey: admin
    secretKey: admin123
    bucket: di-bucket

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    lazy-loading-enabled: true  # Lazy Loading 활성화
    aggressive-lazy-loading: false  # 필요할 때만 로딩

